import '../globals.css'
import { Inter } from 'next/font/google'
import UserProvider from '@/context/UserContext'
import CabeceroUser from '@/components/NavBarUser'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'User Layout',
  description: 'Generated by create next app',
}

export default function UserLayout({ children }) {
  return (
    <UserProvider>
    <html lang="en">
      <body className={inter.className}>
      <CabeceroUser/>
      {children}
      </body>
    </html>
    </UserProvider>
  )
}
