import './globals.css'
import { Inter } from 'next/font/google';
import UserProvider from '@/context/UserContext';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Public Layout',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en">
        <body className={inter.className}>
          {children}
          <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.0.0/flowbite.min.js" />
        </body>
      </html>
    </UserProvider>
  )
}
