import './globals.css'
import { Inter } from 'next/font/google'
import Cabecero from '@/components/NavBar'
import UserProvider from '@/context/UserContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Public Layout',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <UserProvider>
    <html lang="en">
      <body className={inter.className}>
      {children}
      </body>
    </html>
    </UserProvider>
  )
}
