import '../globals.css'
import { Inter } from 'next/font/google'
import Cabecero from '@/components/NavBar'
import UserProvider from '@/context/UserContext'
import CabeceroMaestro from '@/components/NavBarMaestro'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Maestro Mayor de Obras Layout',
  description: 'Generated by create next app',
}

export default function MaestroUser({ children }) {
  return (
    <UserProvider>
    <html lang="en">
      <body className={inter.className}>
      <CabeceroMaestro/>
      {children}
      </body>
    </html>
    </UserProvider>
  )
}
